---
title: "Reflections"

description: |
  Reflections on the course-related learning and participation
---

In this project, I conducted an assessment of the independent variables that have the potential of affecting the dependent variables which include the general test performance as well as the pass rate of the student. With the help of different statistical models and writing R programs, I analyzed the impact that study hours, sleep hours, stress levels, and previous GPA have on academic success.

## Course Learning Objectives


### 1. Describe probability as a foundation of statistical modeling, including inference and maximum likelihood estimation

In my project, I applied the binary logistic regression whereby I hoped to show the likelihood of the students passing the examination and this depended on study hours, sleep hours, stress levels, and previous grade point average.

The application of a logistic regression model is  useful for further explaining how the probability concepts underlie the framework of statistical modeling. The maximum likelihood estimation enabled me to identify the model most appropriate to estimate the probability to pass the exam, an aspect that proved that probability informs inference and decision making while conducting statistics.

### 2. Determine and apply the appropriate generalized linear model for a specific data context

In the given analysis I have employed both the linear regression and logistic regression techniques. I used a linear model for fixed effects and for the continuous outcome variable of examination scores while using a logistic model for the categorical dependent variable, pass/fail in the examination.

In case of the continuous outcome, I applied the linear regression analysis to determine the relationship between the study hours, sleep hours, and stress level/previous GPA with the exam scores. For the binary outcome, I used Logistic regression to predict the probability of passing. This proved my competency on how to choose and use the right generalized linear model according to the density of the data and the research questions.

### 3. Conduct model selection for a set of candidate models

Here, model selection was done through stepwise selection for regression based on linearity and LASSO regression for logistic regression model.

Backward elimination also known as backward step-wise method involved in elimination of insignificant variables from the model with the help of certain statistical measures. For the logistic model, LASSO was employed to determine the best number of predictors that can be used while at the same time avoiding over-fitting. This process also demonstrated that I can select and choose the best model from two or more models.

### 4. Communicate the results of statistical models to a general audience

I ensured that I gave a straightforward and concise analysis of my results at the end of my work.

The summary has provided clear descriptions and elaboration of the relationship between each predictor and the exam performance like the study hours and previous GPA which were given as positive and the stress which was given as negative. Such clear communication made the results easily understandable by anyone in the population as well as exercising corporate understanding on those findings.

### 5. Use programming software
I used R in data simulation, fitting the models, as well as evaluation.

Detailed work-wise, R was very useful in processes such as fitting logistic regression; selection of models using LASSO and performance analysis by ROC curves. This is evident through my ability to adequately use the programming software for statistical modeling and analysis and that stresses my prowess in the use of R on the job.

## Contribution to Course Community

 I actively attended class, discussed with other students about the projects and coursework, and critiqued their work. My participation improved my understanding and benefited the course group by promoting teamwork and assisting fellow students.

